version: '3'
services:
    flask :
        build: . 
        environment: 
            - FLASK_APP=hello.py
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=True
        command:
            gunicorn -w 4 -b 0.0.0.0:5000 hello:app --reload
        ports: 
            - "5000:5000"
        volumes: 
            - ./:/root

 